//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clamp.AddIns.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShanDian.AddIns.Properties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 找不到{0}的Path 的本地化字符串。
        /// </summary>
        internal static string AddIn_BuildItem_NotFoundPath {
            get {
                return ResourceManager.GetString("AddIn_BuildItem_NotFoundPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到{0}ConditionEvaluator。 的本地化字符串。
        /// </summary>
        internal static string AddIn_Condition_Evaluator_NotFound {
            get {
                return ResourceManager.GetString("AddIn_Condition_Evaluator_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manifest节点内容不能为空 的本地化字符串。
        /// </summary>
        internal static string AddIn_Manifest_EmptyElement {
            get {
                return ResourceManager.GetString("AddIn_Manifest_EmptyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manifest节点要求没有属性 的本地化字符串。
        /// </summary>
        internal static string AddIn_Manifest_HaveAttribute {
            get {
                return ResourceManager.GetString("AddIn_Manifest_HaveAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到对应的{0}Path 的本地化字符串。
        /// </summary>
        internal static string AddIn_TreePath_NotFound {
            get {
                return ResourceManager.GetString("AddIn_TreePath_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}是非合元素节点。元素节点必须是Or,And,Not 的本地化字符串。
        /// </summary>
        internal static string AddIn_Xml_ComplexCondition_InValidate {
            get {
                return ResourceManager.GetString("AddIn_Xml_ComplexCondition_InValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}是非合元素节点。元素节点必须是Or,And,Not,Condition 的本地化字符串。
        /// </summary>
        internal static string AddIn_Xml_Condition_InValidate {
            get {
                return ResourceManager.GetString("AddIn_Xml_Condition_InValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Alert_Title_Hint {
            get {
                return ResourceManager.GetString("Alert_Title_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名字不能为空的 的本地化字符串。
        /// </summary>
        internal static string Modules_AddInReference_NameNotEmpty {
            get {
                return ResourceManager.GetString("Modules_AddInReference_NameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到{0}类型的对象。 的本地化字符串。
        /// </summary>
        internal static string Singleton_ObjectNotFoundException {
            get {
                return ResourceManager.GetString("Singleton_ObjectNotFoundException", resourceCulture);
            }
        }
    }
}
