//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShanDian.UIShell.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SDResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SDResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShanDian.UIShell.Properties.SDResources", typeof(SDResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 我知道了 的本地化字符串。
        /// </summary>
        internal static string Activited_BtnHelpConfirm {
            get {
                return ResourceManager.GetString("Activited_BtnHelpConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Activited_BtnHelpConfirmText {
            get {
                return ResourceManager.GetString("Activited_BtnHelpConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        internal static string Activited_BtnMainBack {
            get {
                return ResourceManager.GetString("Activited_BtnMainBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激活 的本地化字符串。
        /// </summary>
        internal static string Activited_BtnMainNext {
            get {
                return ResourceManager.GetString("Activited_BtnMainNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        internal static string Activited_BtnSubBack {
            get {
                return ResourceManager.GetString("Activited_BtnSubBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激活 的本地化字符串。
        /// </summary>
        internal static string Activited_BtnSubNext {
            get {
                return ResourceManager.GetString("Activited_BtnSubNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 什么是善点主机和分机？ 的本地化字符串。
        /// </summary>
        internal static string Activited_InstallDescription {
            get {
                return ResourceManager.GetString("Activited_InstallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装善点主机 的本地化字符串。
        /// </summary>
        internal static string Activited_InstallMainframe {
            get {
                return ResourceManager.GetString("Activited_InstallMainframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择您要安装的类型 的本地化字符串。
        /// </summary>
        internal static string Activited_InstallModeTitle {
            get {
                return ResourceManager.GetString("Activited_InstallModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在安装分机，请稍候… 的本地化字符串。
        /// </summary>
        internal static string Activited_InstallSubBusyText {
            get {
                return ResourceManager.GetString("Activited_InstallSubBusyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装分机 的本地化字符串。
        /// </summary>
        internal static string Activited_InstallSubButton {
            get {
                return ResourceManager.GetString("Activited_InstallSubButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装失败。连接不上主机服务器 的本地化字符串。
        /// </summary>
        internal static string Activited_InstallSubError {
            get {
                return ResourceManager.GetString("Activited_InstallSubError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP格式设置错误! 的本地化字符串。
        /// </summary>
        internal static string Activited_InValidationIp {
            get {
                return ResourceManager.GetString("Activited_InValidationIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 善点主机，是指能够独立运行并提供数据存储和计算服务、带有操作界面的终端，每家门店有且仅有一个主机； 的本地化字符串。
        /// </summary>
        internal static string Activited_MainFrameText {
            get {
                return ResourceManager.GetString("Activited_MainFrameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如何获取门店编号? 的本地化字符串。
        /// </summary>
        internal static string Activited_MainHelpDescription {
            get {
                return ResourceManager.GetString("Activited_MainHelpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 门店编号是，是服务商提供给门店的17位数字串、是善点为门店提供服务的识别码；
        ///如果忘记门店编号，请联系服务商或拨打客服电话 40080-51780，以获得更多帮助 的本地化字符串。
        /// </summary>
        internal static string Activited_MainHowDescription {
            get {
                return ResourceManager.GetString("Activited_MainHowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在激活中..... 的本地化字符串。
        /// </summary>
        internal static string Activited_ProgressBarIndeterminateText {
            get {
                return ResourceManager.GetString("Activited_ProgressBarIndeterminateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激活失败，原因：{0} 的本地化字符串。
        /// </summary>
        internal static string Activited_RestCodeActivitedFailure {
            get {
                return ResourceManager.GetString("Activited_RestCodeActivitedFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激活成功 的本地化字符串。
        /// </summary>
        internal static string Activited_RestCodeActivitedSuccess {
            get {
                return ResourceManager.GetString("Activited_RestCodeActivitedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入门店编号 的本地化字符串。
        /// </summary>
        internal static string Activited_RestCodeHint {
            get {
                return ResourceManager.GetString("Activited_RestCodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 门店编号不能为空 的本地化字符串。
        /// </summary>
        internal static string Activited_RestCodeNotBlank {
            get {
                return ResourceManager.GetString("Activited_RestCodeNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 远程主机访问失败 的本地化字符串。
        /// </summary>
        internal static string Activited_ServerNotAccess {
            get {
                return ResourceManager.GetString("Activited_ServerNotAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 善点分机，是指仅安装操作界面的终端，通过连接善点主机服务来实现业务功能，每家门店可以安装多个分机。 的本地化字符串。
        /// </summary>
        internal static string Activited_SubFrameText {
            get {
                return ResourceManager.GetString("Activited_SubFrameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如何获取IP地址? 的本地化字符串。
        /// </summary>
        internal static string Activited_SubHelpDescription {
            get {
                return ResourceManager.GetString("Activited_SubHelpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这里是使用善点主机的电脑的固定IP地址，需要在主机所在电脑进行查询操作：
        ///
        ///对于Windows XP 版本的系统：
        ///方法一：如果右下角系统托盘区有本地连接的小电脑，双击小电脑→支持，就可以看到本机IP地址。无线连接也是一样。
        ///方法二：点击开始→运行，输入cmd /k ipconfig，IP address后面的就是本机IP地址。
        ///
        ///对于WIN7（含）以上的系统：
        ///方法一：单击系统托盘区的网络连接的小电脑→打开网络和共享中心→查看活动网络连接，根据情况选择本地连接或者无线连接→详细信息里面那里就可以看到本机IP地址。
        ///方法二：点击开始→运行，输入cmd /k ipconfig，IP address后面的就是本机IP地址。 的本地化字符串。
        /// </summary>
        internal static string Activited_SubHowDescription {
            get {
                return ResourceManager.GetString("Activited_SubHowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入主机IP地址 的本地化字符串。
        /// </summary>
        internal static string Activited_SubIpHint {
            get {
                return ResourceManager.GetString("Activited_SubIpHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主机IP不能为空 的本地化字符串。
        /// </summary>
        internal static string Activited_SubIpNotBlank {
            get {
                return ResourceManager.GetString("Activited_SubIpNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在验证编号，请稍候… 的本地化字符串。
        /// </summary>
        internal static string Activited_ValidateBusyText {
            get {
                return ResourceManager.GetString("Activited_ValidateBusyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 什么是善点主机？ 的本地化字符串。
        /// </summary>
        internal static string Activited_WhatMainFrame {
            get {
                return ResourceManager.GetString("Activited_WhatMainFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 什么是善点分机？ 的本地化字符串。
        /// </summary>
        internal static string Activited_WhatSubFrame {
            get {
                return ResourceManager.GetString("Activited_WhatSubFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理设置 的本地化字符串。
        /// </summary>
        internal static string ActivitedView_ProxyText {
            get {
                return ResourceManager.GetString("ActivitedView_ProxyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装善点分机 的本地化字符串。
        /// </summary>
        internal static string Activtied_InstallSubframe {
            get {
                return ResourceManager.GetString("Activtied_InstallSubframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 善点 的本地化字符串。
        /// </summary>
        internal static string Activtied_Title {
            get {
                return ResourceManager.GetString("Activtied_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证 的本地化字符串。
        /// </summary>
        internal static string Activtied_ValidateButton {
            get {
                return ResourceManager.GetString("Activtied_ValidateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证激活善点 的本地化字符串。
        /// </summary>
        internal static string Activtied_ValidateRestCodeTitle {
            get {
                return ResourceManager.GetString("Activtied_ValidateRestCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行环境 的本地化字符串。
        /// </summary>
        internal static string Alert_Envir_Title {
            get {
                return ResourceManager.GetString("Alert_Envir_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Alert_Error_Title {
            get {
                return ResourceManager.GetString("Alert_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理地址格式不正确 的本地化字符串。
        /// </summary>
        internal static string AuthorityView_InValidteIpText {
            get {
                return ResourceManager.GetString("AuthorityView_InValidteIpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口号必须是数字 的本地化字符串。
        /// </summary>
        internal static string AuthorityView_InValidtePortText {
            get {
                return ResourceManager.GetString("AuthorityView_InValidtePortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录中 的本地化字符串。
        /// </summary>
        internal static string AuthorityView_LoginingText {
            get {
                return ResourceManager.GetString("AuthorityView_LoginingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string AuthorityView_LoginText {
            get {
                return ResourceManager.GetString("AuthorityView_LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能空 的本地化字符串。
        /// </summary>
        internal static string AuthorityView_PasswordBlank {
            get {
                return ResourceManager.GetString("AuthorityView_PasswordBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入密码 的本地化字符串。
        /// </summary>
        internal static string AuthorityView_PasswordHintText {
            get {
                return ResourceManager.GetString("AuthorityView_PasswordHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        internal static string AuthorityView_ProxyAddressText {
            get {
                return ResourceManager.GetString("AuthorityView_ProxyAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string AuthorityView_ProxyBtnOkText {
            get {
                return ResourceManager.GetString("AuthorityView_ProxyBtnOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试 的本地化字符串。
        /// </summary>
        internal static string AuthorityView_ProxyBtnTestText {
            get {
                return ResourceManager.GetString("AuthorityView_ProxyBtnTestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果本机不能上网，可设置网络代理 的本地化字符串。
        /// </summary>
        internal static string AuthorityView_ProxyDesc {
            get {
                return ResourceManager.GetString("AuthorityView_ProxyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理连接失败 的本地化字符串。
        /// </summary>
        internal static string AuthorityView_ProxyFailureText {
            get {
                return ResourceManager.GetString("AuthorityView_ProxyFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string AuthorityView_ProxyPasswordText {
            get {
                return ResourceManager.GetString("AuthorityView_ProxyPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口 的本地化字符串。
        /// </summary>
        internal static string AuthorityView_ProxyPortText {
            get {
                return ResourceManager.GetString("AuthorityView_ProxyPortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理连接成功 的本地化字符串。
        /// </summary>
        internal static string AuthorityView_ProxySuccessText {
            get {
                return ResourceManager.GetString("AuthorityView_ProxySuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络代理 的本地化字符串。
        /// </summary>
        internal static string AuthorityView_ProxyText {
            get {
                return ResourceManager.GetString("AuthorityView_ProxyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        internal static string AuthorityView_ProxyTypeText {
            get {
                return ResourceManager.GetString("AuthorityView_ProxyTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        internal static string AuthorityView_ProxyUsernameText {
            get {
                return ResourceManager.GetString("AuthorityView_ProxyUsernameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住密码 的本地化字符串。
        /// </summary>
        internal static string AuthorityView_RememberMeText {
            get {
                return ResourceManager.GetString("AuthorityView_RememberMeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号不能空 的本地化字符串。
        /// </summary>
        internal static string AuthorityView_UsernameBlank {
            get {
                return ResourceManager.GetString("AuthorityView_UsernameBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入账号 的本地化字符串。
        /// </summary>
        internal static string AuthorityView_UsernameHintText {
            get {
                return ResourceManager.GetString("AuthorityView_UsernameHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载应用 的本地化字符串。
        /// </summary>
        internal static string BusyIndicator_BusyText {
            get {
                return ResourceManager.GetString("BusyIndicator_BusyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览器的组件不完全 的本地化字符串。
        /// </summary>
        internal static string CheckExecute_BrowerCheckDependencies {
            get {
                return ResourceManager.GetString("CheckExecute_BrowerCheckDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在检测运行环境...... 的本地化字符串。
        /// </summary>
        internal static string CheckExecute_CheckDotNet {
            get {
                return ResourceManager.GetString("CheckExecute_CheckDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前的执行环境不合适 的本地化字符串。
        /// </summary>
        internal static string CheckExecute_CheckDotNetError {
            get {
                return ResourceManager.GetString("CheckExecute_CheckDotNetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请安装.NetFramework 4.0 的本地化字符串。
        /// </summary>
        internal static string CheckExecute_Dotnet {
            get {
                return ResourceManager.GetString("CheckExecute_Dotnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台通信出错 的本地化字符串。
        /// </summary>
        internal static string CheckExecute_ErrorNetworkService {
            get {
                return ResourceManager.GetString("CheckExecute_ErrorNetworkService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在启动善点..... 的本地化字符串。
        /// </summary>
        internal static string CheckExecute_FinalService {
            get {
                return ResourceManager.GetString("CheckExecute_FinalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本机服务有异常，请检查重启WindowService服务 的本地化字符串。
        /// </summary>
        internal static string CheckExecute_FinalServiceError {
            get {
                return ResourceManager.GetString("CheckExecute_FinalServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在检测数据是否完整...... 的本地化字符串。
        /// </summary>
        internal static string CheckExecute_Initialized {
            get {
                return ResourceManager.GetString("CheckExecute_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在打开应用程序...... 的本地化字符串。
        /// </summary>
        internal static string CheckExecute_OpeningApplication {
            get {
                return ResourceManager.GetString("CheckExecute_OpeningApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载配置文件...... 的本地化字符串。
        /// </summary>
        internal static string CheckExecute_ReadIniFile {
            get {
                return ResourceManager.GetString("CheckExecute_ReadIniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在连接善点主机..... 的本地化字符串。
        /// </summary>
        internal static string CheckExecute_Server {
            get {
                return ResourceManager.GetString("CheckExecute_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务端服务异常，请检查重启善点服务 的本地化字符串。
        /// </summary>
        internal static string CheckExecute_ServerError {
            get {
                return ResourceManager.GetString("CheckExecute_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务端通信异常，请检查重启善点服务 的本地化字符串。
        /// </summary>
        internal static string CheckExecute_ServerNetError {
            get {
                return ResourceManager.GetString("CheckExecute_ServerNetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Connect {
            get {
                object obj = ResourceManager.GetObject("Connect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;title&gt;善点客户端&lt;/title&gt;
        ///    &lt;style&gt;
        ///
        ///
        ///        body {
        ///            background-color: #ffffff;
        ///        }
        ///
        ///        .connect-div {
        ///            width: 103px;
        ///            height: 100px;
        ///            background-image: url(custom://SD-proxy.chidaoni.com/assets/image/Connect.svg);
        ///            margin: 0 auto;
        ///        }
        ///
        ///        .center-div {
        ///            position: absolute;
        ///            margin: auto;
        ///            top: 0;
        ///            right: 0; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string default_404 {
            get {
                return ResourceManager.GetString("default_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Dialog_Btn_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string Dialog_Btn_OK {
            get {
                return ResourceManager.GetString("Dialog_Btn_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否确定退出善点？ 的本地化字符串。
        /// </summary>
        internal static string Dialog_Exit_Text {
            get {
                return ResourceManager.GetString("Dialog_Exit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Dialog_Title {
            get {
                return ResourceManager.GetString("Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略 的本地化字符串。
        /// </summary>
        internal static string DialogKeyHot_BottonIgore {
            get {
                return ResourceManager.GetString("DialogKeyHot_BottonIgore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string DialogKeyHot_BottonModify {
            get {
                return ResourceManager.GetString("DialogKeyHot_BottonModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下次不再提醒 的本地化字符串。
        /// </summary>
        internal static string DialogkeyHot_NextHint {
            get {
                return ResourceManager.GetString("DialogkeyHot_NextHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本机善点的快捷键被其他软件占用，存在冲突！ 的本地化字符串。
        /// </summary>
        internal static string DialogkeyHot_Text_Line1 {
            get {
                return ResourceManager.GetString("DialogkeyHot_Text_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建议修改其他软件的快捷键，以保证善点可用 的本地化字符串。
        /// </summary>
        internal static string DialogkeyHot_Text_Line2 {
            get {
                return ResourceManager.GetString("DialogkeyHot_Text_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 或修改善点的快捷键。 的本地化字符串。
        /// </summary>
        internal static string DialogkeyHot_Text_Line3 {
            get {
                return ResourceManager.GetString("DialogkeyHot_Text_Line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快捷键冲突 的本地化字符串。
        /// </summary>
        internal static string DialogkeyHot_Title {
            get {
                return ResourceManager.GetString("DialogkeyHot_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 善点主机已安装在其他设备，请返回安装分机；如果一定要在本机重新安装善点主机，请联系客服（40080-51780）解绑后，再继续安装 的本地化字符串。
        /// </summary>
        internal static string Error_ExistDriver {
            get {
                return ResourceManager.GetString("Error_ExistDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号未授权，请联系门店管理员 的本地化字符串。
        /// </summary>
        internal static string Error_InValidAuth {
            get {
                return ResourceManager.GetString("Error_InValidAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号或密码错误 的本地化字符串。
        /// </summary>
        internal static string Error_InValidUsername {
            get {
                return ResourceManager.GetString("Error_InValidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该账号无任何权限，请联系管理员 的本地化字符串。
        /// </summary>
        internal static string Error_NoAction {
            get {
                return ResourceManager.GetString("Error_NoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统繁忙, 请稍后重试 的本地化字符串。
        /// </summary>
        internal static string Error_OtherError {
            get {
                return ResourceManager.GetString("Error_OtherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新启动 的本地化字符串。
        /// </summary>
        internal static string FrmError_BtnReset {
            get {
                return ResourceManager.GetString("FrmError_BtnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 善点 的本地化字符串。
        /// </summary>
        internal static string FrmError_Titile {
            get {
                return ResourceManager.GetString("FrmError_Titile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 贴地气的/餐厅信息化/智能工具 的本地化字符串。
        /// </summary>
        internal static string FrmSplash_VersionTitle {
            get {
                return ResourceManager.GetString("FrmSplash_VersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快捷键冲突，请重新设置 的本地化字符串。
        /// </summary>
        internal static string Hotkey_AlreadyExist {
            get {
                return ResourceManager.GetString("Hotkey_AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务端通信异常，请检查重启善点服务 的本地化字符串。
        /// </summary>
        internal static string HttpAccessor_BadData {
            get {
                return ResourceManager.GetString("HttpAccessor_BadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到相关的身分验证 的本地化字符串。
        /// </summary>
        internal static string HttpAccessor_NotFoundTokenInfo {
            get {
                return ResourceManager.GetString("HttpAccessor_NotFoundTokenInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到相关的用户信息 的本地化字符串。
        /// </summary>
        internal static string HttpAccessor_NotFoundUserInfo {
            get {
                return ResourceManager.GetString("HttpAccessor_NotFoundUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打不到相关的用户权限 的本地化字符串。
        /// </summary>
        internal static string HttpAccessor_NotFoundUserPermission {
            get {
                return ResourceManager.GetString("HttpAccessor_NotFoundUserPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该账号无任何权限, 请联系管理员 的本地化字符串。
        /// </summary>
        internal static string HttpAccessor_NotPermissions {
            get {
                return ResourceManager.GetString("HttpAccessor_NotPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统繁忙, 请稍后重试 的本地化字符串。
        /// </summary>
        internal static string HttpAccessor_SystemBusy {
            get {
                return ResourceManager.GetString("HttpAccessor_SystemBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动信息加载完毕 的本地化字符串。
        /// </summary>
        internal static string HydraWorkbench_AfterRunWorkbenchText {
            get {
                return ResourceManager.GetString("HydraWorkbench_AfterRunWorkbenchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载启动信息中..... 的本地化字符串。
        /// </summary>
        internal static string HydraWorkbench_BeforeRunWorkbenchText {
            get {
                return ResourceManager.GetString("HydraWorkbench_BeforeRunWorkbenchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置信息加载完毕 的本地化字符串。
        /// </summary>
        internal static string HydraWorkbench_EndBuildText {
            get {
                return ResourceManager.GetString("HydraWorkbench_EndBuildText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载配置信息中..... 的本地化字符串。
        /// </summary>
        internal static string HydraWorkbench_StartBuildText {
            get {
                return ResourceManager.GetString("HydraWorkbench_StartBuildText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string MainWindow_NotifyIcon_Exit {
            get {
                return ResourceManager.GetString("MainWindow_NotifyIcon_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示悬浮窗 的本地化字符串。
        /// </summary>
        internal static string MainWindow_NotifyIcon_FloatDisplay {
            get {
                return ResourceManager.GetString("MainWindow_NotifyIcon_FloatDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏悬浮窗 的本地化字符串。
        /// </summary>
        internal static string MainWindow_NotifyIcon_FloatHide {
            get {
                return ResourceManager.GetString("MainWindow_NotifyIcon_FloatHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string MainWindow_NotifyIcon_Open {
            get {
                return ResourceManager.GetString("MainWindow_NotifyIcon_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 善点 的本地化字符串。
        /// </summary>
        internal static string MainWindow_ProductName {
            get {
                return ResourceManager.GetString("MainWindow_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请使用管理员角色运行善点 的本地化字符串。
        /// </summary>
        internal static string Program_IsAdminstrator {
            get {
                return ResourceManager.GetString("Program_IsAdminstrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SettingFile_ClosingBracketMissing {
            get {
                return ResourceManager.GetString("SettingFile_ClosingBracketMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SettingFile_ClosingQuoteMissing {
            get {
                return ResourceManager.GetString("SettingFile_ClosingQuoteMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SettingFile_Comment_NotAllowedChar {
            get {
                return ResourceManager.GetString("SettingFile_Comment_NotAllowedChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SettingFile_Comment_NotAllowedZeroCharacter {
            get {
                return ResourceManager.GetString("SettingFile_Comment_NotAllowedZeroCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SettingFile_EquatMissing {
            get {
                return ResourceManager.GetString("SettingFile_EquatMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SettingFile_Exception_SectionItemValueCast {
            get {
                return ResourceManager.GetString("SettingFile_Exception_SectionItemValueCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SettingFile_NotFoundFileName {
            get {
                return ResourceManager.GetString("SettingFile_NotFoundFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SettingFile_SectionItem_Existed {
            get {
                return ResourceManager.GetString("SettingFile_SectionItem_Existed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SettingFile_SectionItem_JaggedArrays {
            get {
                return ResourceManager.GetString("SettingFile_SectionItem_JaggedArrays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SettingFile_SectionItem_Name_NotNull {
            get {
                return ResourceManager.GetString("SettingFile_SectionItem_Name_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SettingFile_SectionItem_ShouldArray {
            get {
                return ResourceManager.GetString("SettingFile_SectionItem_ShouldArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SettingFile_SectionItem_TypeShouldArray {
            get {
                return ResourceManager.GetString("SettingFile_SectionItem_TypeShouldArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SettingFile_SectionItemNameMissing {
            get {
                return ResourceManager.GetString("SettingFile_SectionItemNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SettingFile_TakenMissing {
            get {
                return ResourceManager.GetString("SettingFile_TakenMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SettingFile_TypeStringConverte_Existed {
            get {
                return ResourceManager.GetString("SettingFile_TypeStringConverte_Existed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SettingFile_TypeStringConverte_NoRegiester {
            get {
                return ResourceManager.GetString("SettingFile_TypeStringConverte_NoRegiester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Singleton_ObjectNotFoundException {
            get {
                return ResourceManager.GetString("Singleton_ObjectNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap u32 {
            get {
                object obj = ResourceManager.GetObject("u32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap u37 {
            get {
                object obj = ResourceManager.GetObject("u37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
