//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clamp.MUI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clamp.MUI.Properties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 重新启动 的本地化字符串。
        /// </summary>
        internal static string FrmError_BtnReset {
            get {
                return ResourceManager.GetString("FrmError_BtnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 善点 的本地化字符串。
        /// </summary>
        internal static string FrmError_Titile {
            get {
                return ResourceManager.GetString("FrmError_Titile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string FrmMainChromium_NotifyIcon_Exit {
            get {
                return ResourceManager.GetString("FrmMainChromium_NotifyIcon_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示悬浮窗 的本地化字符串。
        /// </summary>
        internal static string FrmMainChromium_NotifyIcon_FloatDisplay {
            get {
                return ResourceManager.GetString("FrmMainChromium_NotifyIcon_FloatDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏悬浮窗 的本地化字符串。
        /// </summary>
        internal static string FrmMainChromium_NotifyIcon_FloatHide {
            get {
                return ResourceManager.GetString("FrmMainChromium_NotifyIcon_FloatHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string FrmMainChromium_NotifyIcon_Open {
            get {
                return ResourceManager.GetString("FrmMainChromium_NotifyIcon_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在打开应用程序 的本地化字符串。
        /// </summary>
        internal static string FrmSplash_OpenApplication {
            get {
                return ResourceManager.GetString("FrmSplash_OpenApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V{0} 的本地化字符串。
        /// </summary>
        internal static string FrmSplash_VersionText {
            get {
                return ResourceManager.GetString("FrmSplash_VersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最贴地气的/餐厅信息化/智能工具 的本地化字符串。
        /// </summary>
        internal static string FrmSplash_VersionTitle {
            get {
                return ResourceManager.GetString("FrmSplash_VersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string MessageBox_AlertTitle {
            get {
                return ResourceManager.GetString("MessageBox_AlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请使用管理员角色运行善点 的本地化字符串。
        /// </summary>
        internal static string Program_IsAdminstrator {
            get {
                return ResourceManager.GetString("Program_IsAdminstrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务端通信异常，请检查重启善点服务 的本地化字符串。
        /// </summary>
        internal static string WinFormBridge_BadData {
            get {
                return ResourceManager.GetString("WinFormBridge_BadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string WinFormBridge_NotFoundTokenInfo {
            get {
                return ResourceManager.GetString("WinFormBridge_NotFoundTokenInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到相关的用户信息 的本地化字符串。
        /// </summary>
        internal static string WinFormBridge_NotFoundUserInfo {
            get {
                return ResourceManager.GetString("WinFormBridge_NotFoundUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统繁忙, 请稍后重试 的本地化字符串。
        /// </summary>
        internal static string WinFormBridge_SystemBusy {
            get {
                return ResourceManager.GetString("WinFormBridge_SystemBusy", resourceCulture);
            }
        }
    }
}
